spring:
  output:
    ansi:
      enabled: DETECT
  zipkin:
    baseUrl: http://localhost:9411
  sleuth:
    log:
      slf4j:
        enabled: true
    sampler:
      probability: 1.0
  application:
    name: sleuth-logging

server:
  port: 8084
  servlet:
    contextPath: /local
  compression:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761

java:
  util:
    logging:
      manager: org.apache.logging.log4j.jul.LogManager
      
logging:
  level:
    org.springframework.web: ERROR
    com.home.dguymon: DEBUG
  pattern:
    console: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] [${spring.application.name:-},%X{X-B3-TraceId},%X{X-B3-SpanId},%X{X-B3-ParentSpanId},%X{X-Span-Export}] %c{1} - %msg%n"
    file: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"
  file: logs/logfile.txt