spring:
  output:
    ansi:
      enabled: DETECT
  zipkin:
    baseUrl: http://localhost:9411
  sleuth:
    log:
      slf4j:
        enabled: true
    sampler:
      probability: 1.0
  application:
    name: sleuth-logging
  cloud:
    client:
      hostname: localhost

server:
  port: 8084
  servlet:
    contextPath: /${spring.application.name}
  compression:
    enabled: true

#cloud:
#  aws:
#    rds:
#      dguymon-postgresql: 
#        username: dguymon
#        password: rdsXenosaga2!
#        readReplicaSupport: false

eureka:
  cloud:
    discovery:
      enabled: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthCheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /${spring.application.name}/actuator/info
    healthCheckUrlPath: /${spring.application.name}/actuator/health
    nonSecurePortEnabled: true
    securePortEnabled: false

java:
  util:
    logging:
      manager: org.apache.logging.log4j.jul.LogManager
      
logging:
  level:
    org.springframework.web: ERROR
    com.home.dguymon: DEBUG
  pattern:
    console: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] [${spring.application.name:-},%X{X-B3-TraceId},%X{X-B3-SpanId},%X{X-B3-ParentSpanId},%X{X-Span-Export}] %c{1} - %msg%n"
    file: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"
  file: logs/logfile.log

custom:
  api:
    version: v1
  dynamodb:
    table: capability
  